name: Build Library

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [arm64, x64, x86]
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-i686-toolchain
            mingw-w64-cross-toolchain
            meson
            ninja

      - name: Build
        shell: cmd
        run: |
          rem Ensure MSYS2 tools (meson, ninja) and compilers are in the PATH for cmd
          set PATH=%MSYS2_INSTALL_DIR%\usr\bin;%MSYS2_INSTALL_DIR%\mingw64\bin;%MSYS2_INSTALL_DIR%\mingw32\bin;%PATH%
          
          rem Optional: Verify PATH for debugging
          rem echo "Current PATH in cmd:"
          rem echo %PATH%

          rem Now run the build script
          build.bat
        env:
          ARCHITECTURES: ${{ matrix.arch }}



      - name: Verify build directory
        shell: bash
        run: |
          echo "Build directory contents:"
          ls -R build || true

      - name: Collect artifacts
        shell: bash
        run: |
          mkdir -p artifacts
          echo "Copying build outputs..."
          
          # For each architecture
          for arch in ${{ matrix.arch }}; do
            echo "Processing $arch..."
            # Find and copy all DLLs, LIBs, and static libs
            find "build/build_static_${arch}" -name "*.dll" -exec cp {} artifacts/ \;
          done
          
          echo "Final artifacts:"
          ls -lh artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webrtc-audio-processing-${{ matrix.arch }}
          path: artifacts/
          if-no-files-found: error