name: Build WebRTC Audio Processing

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          # macOS builds
          - os: macos-latest
            rid: osx-x64
            platform: macOS
            arch: x86_64
            toolchain: clang
            cross_file: ""

          # Android builds
          - os: ubuntu-latest
            rid: android-arm
            platform: Android
            arch: armeabi-v7a
            toolchain: clang
            cross_file: "android-arm.crossfile"
            compiler_prefix: "armv7a-linux-androideabi"


    name: Build for ${{ matrix.platform }} - ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Setup Python and Meson
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Meson and Ninja
        run: pip install meson ninja --upgrade

      # Install MinGW for Windows builds
      - name: Set up MinGW (Windows - x64)
        if: matrix.platform == 'Windows' && matrix.arch == 'x64'
        uses: deevroman/setup-mingw@0.0.1
        with:
          platform: x64
          static: any

      - name: Set up MinGW (Windows - x86)
        if: matrix.platform == 'Windows' && matrix.arch == 'x86'
        uses: deevroman/setup-mingw@0.0.1
        with:
          platform: any
          static: any

      # Linux dependencies
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest' && matrix.platform == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config
          
          # For cross-compilation
          if [ "${{ matrix.rid }}" == "linux-arm" ]; then
            sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          elif [ "${{ matrix.rid }}" == "linux-arm64" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          fi

      # Android setup
      - name: Set up Android NDK
        if: matrix.platform == 'Android'
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          add-to-path: false

      - name: Configure environment for Android
        if: matrix.platform == 'Android'
        shell: bash
        run: |
          echo "NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "TOOLCHAIN_ROOT=${NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64" >> $GITHUB_ENV

      # Print the NDK Root
      - name: Print NDK Root
        if: matrix.platform == 'Android'
        shell: bash
        run: |
          echo "The NDK Root is: $NDK_ROOT"
          echo "The Toolchain Root is: $TOOLCHAIN_ROOT"
          # List contents of the build directory before copying
          echo "Listing contents of Toolchain: $TOOLCHAIN_ROOT"
          ls -l "/opt/hostedtoolcache/ndk/r26d/x64/toolchains/llvm/prebuilt/linux-x86_64/bin/"


      - name: Install Xcode Command Line Tools (iOS)
        if: matrix.platform == 'iOS'
        run: |
          xcode-select --install || true
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      # Install Homebrew LLVM for iOS builds
      - name: Install Homebrew LLVM (IOS)
        if: matrix.platform == 'iOS'
        run: |
          brew update
          brew install llvm
          echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
          echo "/opt/homebrew/opt/llvm/lib" >> $GITHUB_PATH
          echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> /Users/runner/.bash_profile

      # Configure Meson
      - name: Configure Meson
        shell: bash
        run: |
          BUILD_DIR="build_${{ matrix.rid }}"
          EXTRA_ARGS=""
          
          if [ -n "${{ matrix.cross_file }}" ]; then
            meson setup $BUILD_DIR --cross-file crossfiles/${{ matrix.cross_file }} $EXTRA_ARGS
          else
            meson setup $BUILD_DIR $EXTRA_ARGS
          fi

      # Build with Ninja
      - name: Build with Ninja
        shell: bash
        run: |
          BUILD_DIR="build_${{ matrix.rid }}"
          ninja -C $BUILD_DIR

      # Package the artifacts
      - name: Copy and rename artifacts
        shell: bash
        run: |
          BUILD_DIR="build_${{ matrix.rid }}/webrtc/modules/audio_processing"
          OUTPUT_DIR="runtimes/${{ matrix.rid }}/native"
          
          echo "Listing contents of BUILD_DIR: $BUILD_DIR"
          ls -l "$BUILD_DIR"
          
          mkdir -p "$OUTPUT_DIR"
          
          if [ "${{ matrix.platform }}" == "Windows" ]; then
            cp "$BUILD_DIR"/*.dll "$OUTPUT_DIR/webrtc-apm.dll"
          elif [ "${{ matrix.platform }}" == "iOS" ] || [ "${{ matrix.platform }}" == "macOS" ]; then
            cp "$BUILD_DIR/libwebrtc-audio-processing-*.dylib" "$OUTPUT_DIR/libwebrtc-apm.dylib"
          else
            cp "$BUILD_DIR"/*.so "$OUTPUT_DIR/libwebrtc-apm.so"
          fi
          
          echo "Copied artifact to:"
          ls -l "$OUTPUT_DIR"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.rid }}
          path: runtimes/${{ matrix.rid }}

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create final package
        run: |
          mkdir -p runtimes
          cp -r artifacts/* runtimes/
          zip -r webrtc-audio-processing.zip runtimes

      - name: Upload final package
        uses: actions/upload-artifact@v4
        with:
          name: webrtc-audio-processing
          path: webrtc-audio-processing.zip