name: Build Library

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [arm64, x64, x86]
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-i686-toolchain
            mingw-w64-cross-toolchain
            meson
            ninja

      - name: Build
        shell: cmd
        run: |
          rem Activate the appropriate MSYS2 environment
          rem Adjust -mingw64, -mingw32, or -ucrt64 based on your specific needs if necessary
          rem For general tools like meson/ninja, -msys might be sufficient, but MinGW often needed for compilers
          call "%MSYS2_INSTALL_DIR%\msys2_shell.cmd" -mingw64 -no-start -here -c "echo MSYS2 Environment Activated for cmd"

          rem Verify meson is found now (optional debug step)
          where meson
          
          rem Optional: Verify PATH for debugging
          echo "Current PATH in cmd:"
          echo %PATH%

          rem Now run the build script within the activated environment
          build.bat
        env:
          ARCHITECTURES: ${{ matrix.arch }}
          # MSYSTEM might be needed by some tools/scripts within the MSYS2 env
          # Set it based on the arch if your build.bat depends on it.
          # Example (needs adjustment based on how your build.bat uses ARCHITECTURES):
          # MSYSTEM: ${{ (matrix.arch == 'x64' && 'MINGW64') || (matrix.arch == 'x86' && 'MINGW32') || 'MINGW64' }} # Adjust ARM64 logic as needed



      - name: Verify build directory
        shell: bash
        run: |
          echo "Build directory contents:"
          ls -R build || true

      - name: Collect artifacts
        shell: bash
        run: |
          mkdir -p artifacts
          echo "Copying build outputs..."
          
          # For each architecture
          for arch in ${{ matrix.arch }}; do
            echo "Processing $arch..."
            # Find and copy all DLLs, LIBs, and static libs
            find "build/build_static_${arch}" -name "*.dll" -exec cp {} artifacts/ \;
          done
          
          echo "Final artifacts:"
          ls -lh artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webrtc-audio-processing-${{ matrix.arch }}
          path: artifacts/
          if-no-files-found: error